//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_controle2_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Construction
    {
        public int id { get; set; }
        public Nullable<System.DateTime> dateConstruction { get; set; }
        public string surface { get; set; }
        public Nullable<int> idMacon { get; set; }
    
        public virtual Macon Macon { get; set; }
    }
}
